# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  developmenttoolweb:
    image: developmenttoolweb
    build:
      context: .
      dockerfile: src/DevelopmentTool.Web/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 4701:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
