# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  developmenttoolweb:
    depends_on:
      - redis
    image: developmenttoolweb
    build:
      context: .
      dockerfile: src/DevelopmentTool.Web/Dockerfile
    ports:
      - 4701:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Redis=redis:6379, abortConnect=false, defaultDatabase=0
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
volumes:
  redis_volume_data:
    driver: local